### ISSUE TITLE
`current_checkpoint` is not defined 

### ISSUE THREAD

**Issue by fischerl92** [a-rios/ats-models#4]
Starting a new training with `finetune_mbart.py` results in the following error:
> AttributeError: 'MBartTrainer' object has no attribute 'current_checkpoint'

`current_checkpoint` is not defined if `resume_ckpt` is `None` since the last commit:
https://github.com/a-rios/ats-models/commit/9e14e5fa1aee85a217f2eff619f42ea51ff78bd2#r135527079

**Comment by a-rios** [comment]
sorry, didn't test this properly.. should be fixed with the latest commit. you can also commit fixes yourself btw :)
